// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: protos/gate.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block
type BlockMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreBlockHash  string                 `protobuf:"bytes,1,opt,name=PreBlockHash,proto3" json:"PreBlockHash,omitempty"`
	NodeUID       string                 `protobuf:"bytes,2,opt,name=NodeUID,proto3" json:"NodeUID,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockMeta) Reset() {
	*x = BlockMeta{}
	mi := &file_protos_gate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMeta) ProtoMessage() {}

func (x *BlockMeta) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMeta.ProtoReflect.Descriptor instead.
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{0}
}

func (x *BlockMeta) GetPreBlockHash() string {
	if x != nil {
		return x.PreBlockHash
	}
	return ""
}

func (x *BlockMeta) GetNodeUID() string {
	if x != nil {
		return x.NodeUID
	}
	return ""
}

func (x *BlockMeta) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type BlockData struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SenderUID            string                 `protobuf:"bytes,1,opt,name=SenderUID,proto3" json:"SenderUID,omitempty"`
	SenderRole           int64                  `protobuf:"varint,2,opt,name=SenderRole,proto3" json:"SenderRole,omitempty"`
	SenderPubKey         string                 `protobuf:"bytes,3,opt,name=SenderPubKey,proto3" json:"SenderPubKey,omitempty"`
	Signature            string                 `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	ReceiverUID          string                 `protobuf:"bytes,5,opt,name=ReceiverUID,proto3" json:"ReceiverUID,omitempty"`
	ReceiverRole         int64                  `protobuf:"varint,6,opt,name=ReceiverRole,proto3" json:"ReceiverRole,omitempty"`
	Data                 string                 `protobuf:"bytes,7,opt,name=Data,proto3" json:"Data,omitempty"`
	SmartContractAddress string                 `protobuf:"bytes,8,opt,name=SmartContractAddress,proto3" json:"SmartContractAddress,omitempty"`
	TimeStamp            int64                  `protobuf:"varint,9,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BlockData) Reset() {
	*x = BlockData{}
	mi := &file_protos_gate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockData) ProtoMessage() {}

func (x *BlockData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockData.ProtoReflect.Descriptor instead.
func (*BlockData) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{1}
}

func (x *BlockData) GetSenderUID() string {
	if x != nil {
		return x.SenderUID
	}
	return ""
}

func (x *BlockData) GetSenderRole() int64 {
	if x != nil {
		return x.SenderRole
	}
	return 0
}

func (x *BlockData) GetSenderPubKey() string {
	if x != nil {
		return x.SenderPubKey
	}
	return ""
}

func (x *BlockData) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *BlockData) GetReceiverUID() string {
	if x != nil {
		return x.ReceiverUID
	}
	return ""
}

func (x *BlockData) GetReceiverRole() int64 {
	if x != nil {
		return x.ReceiverRole
	}
	return 0
}

func (x *BlockData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *BlockData) GetSmartContractAddress() string {
	if x != nil {
		return x.SmartContractAddress
	}
	return ""
}

func (x *BlockData) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     string                 `protobuf:"bytes,1,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	BlockMeta     *BlockMeta             `protobuf:"bytes,2,opt,name=BlockMeta,proto3" json:"BlockMeta,omitempty"`
	BlockData     *BlockData             `protobuf:"bytes,3,opt,name=BlockData,proto3" json:"BlockData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_protos_gate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *Block) GetBlockMeta() *BlockMeta {
	if x != nil {
		return x.BlockMeta
	}
	return nil
}

func (x *Block) GetBlockData() *BlockData {
	if x != nil {
		return x.BlockData
	}
	return nil
}

type AddDataResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
	Log           string                 `protobuf:"bytes,2,opt,name=Log,proto3" json:"Log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDataResult) Reset() {
	*x = AddDataResult{}
	mi := &file_protos_gate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDataResult) ProtoMessage() {}

func (x *AddDataResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDataResult.ProtoReflect.Descriptor instead.
func (*AddDataResult) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{3}
}

func (x *AddDataResult) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *AddDataResult) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type ReadDataRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Limit                int64                  `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Skip                 int64                  `protobuf:"varint,2,opt,name=Skip,proto3" json:"Skip,omitempty"`
	SenderUID            string                 `protobuf:"bytes,3,opt,name=SenderUID,proto3" json:"SenderUID,omitempty"`
	SenderRole           int64                  `protobuf:"varint,4,opt,name=SenderRole,proto3" json:"SenderRole,omitempty"`
	SenderPubKey         string                 `protobuf:"bytes,5,opt,name=SenderPubKey,proto3" json:"SenderPubKey,omitempty"`
	ReceiverUID          string                 `protobuf:"bytes,6,opt,name=ReceiverUID,proto3" json:"ReceiverUID,omitempty"`
	ReceiverRole         int64                  `protobuf:"varint,7,opt,name=ReceiverRole,proto3" json:"ReceiverRole,omitempty"`
	BlockHash            string                 `protobuf:"bytes,8,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	PreBlockHash         string                 `protobuf:"bytes,9,opt,name=PreBlockHash,proto3" json:"PreBlockHash,omitempty"`
	NodeUID              string                 `protobuf:"bytes,10,opt,name=NodeUID,proto3" json:"NodeUID,omitempty"`
	TimeStampFrom        int64                  `protobuf:"varint,11,opt,name=TimeStampFrom,proto3" json:"TimeStampFrom,omitempty"`
	TimeStampTo          int64                  `protobuf:"varint,12,opt,name=TimeStampTo,proto3" json:"TimeStampTo,omitempty"`
	SmartContractAddress string                 `protobuf:"bytes,13,opt,name=SmartContractAddress,proto3" json:"SmartContractAddress,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ReadDataRequest) Reset() {
	*x = ReadDataRequest{}
	mi := &file_protos_gate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataRequest) ProtoMessage() {}

func (x *ReadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataRequest.ProtoReflect.Descriptor instead.
func (*ReadDataRequest) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{4}
}

func (x *ReadDataRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReadDataRequest) GetSkip() int64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ReadDataRequest) GetSenderUID() string {
	if x != nil {
		return x.SenderUID
	}
	return ""
}

func (x *ReadDataRequest) GetSenderRole() int64 {
	if x != nil {
		return x.SenderRole
	}
	return 0
}

func (x *ReadDataRequest) GetSenderPubKey() string {
	if x != nil {
		return x.SenderPubKey
	}
	return ""
}

func (x *ReadDataRequest) GetReceiverUID() string {
	if x != nil {
		return x.ReceiverUID
	}
	return ""
}

func (x *ReadDataRequest) GetReceiverRole() int64 {
	if x != nil {
		return x.ReceiverRole
	}
	return 0
}

func (x *ReadDataRequest) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *ReadDataRequest) GetPreBlockHash() string {
	if x != nil {
		return x.PreBlockHash
	}
	return ""
}

func (x *ReadDataRequest) GetNodeUID() string {
	if x != nil {
		return x.NodeUID
	}
	return ""
}

func (x *ReadDataRequest) GetTimeStampFrom() int64 {
	if x != nil {
		return x.TimeStampFrom
	}
	return 0
}

func (x *ReadDataRequest) GetTimeStampTo() int64 {
	if x != nil {
		return x.TimeStampTo
	}
	return 0
}

func (x *ReadDataRequest) GetSmartContractAddress() string {
	if x != nil {
		return x.SmartContractAddress
	}
	return ""
}

type ReadDataResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
	Log           string                 `protobuf:"bytes,2,opt,name=Log,proto3" json:"Log,omitempty"`
	Data          []*Block               `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDataResult) Reset() {
	*x = ReadDataResult{}
	mi := &file_protos_gate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataResult) ProtoMessage() {}

func (x *ReadDataResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataResult.ProtoReflect.Descriptor instead.
func (*ReadDataResult) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{5}
}

func (x *ReadDataResult) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *ReadDataResult) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *ReadDataResult) GetData() []*Block {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_protos_gate_proto protoreflect.FileDescriptor

const file_protos_gate_proto_rawDesc = "" +
	"\n" +
	"\x11protos/gate.proto\x12\x04gate\"g\n" +
	"\tBlockMeta\x12\"\n" +
	"\fPreBlockHash\x18\x01 \x01(\tR\fPreBlockHash\x12\x18\n" +
	"\aNodeUID\x18\x02 \x01(\tR\aNodeUID\x12\x1c\n" +
	"\tTimeStamp\x18\x03 \x01(\x03R\tTimeStamp\"\xb7\x02\n" +
	"\tBlockData\x12\x1c\n" +
	"\tSenderUID\x18\x01 \x01(\tR\tSenderUID\x12\x1e\n" +
	"\n" +
	"SenderRole\x18\x02 \x01(\x03R\n" +
	"SenderRole\x12\"\n" +
	"\fSenderPubKey\x18\x03 \x01(\tR\fSenderPubKey\x12\x1c\n" +
	"\tSignature\x18\x04 \x01(\tR\tSignature\x12 \n" +
	"\vReceiverUID\x18\x05 \x01(\tR\vReceiverUID\x12\"\n" +
	"\fReceiverRole\x18\x06 \x01(\x03R\fReceiverRole\x12\x12\n" +
	"\x04Data\x18\a \x01(\tR\x04Data\x122\n" +
	"\x14SmartContractAddress\x18\b \x01(\tR\x14SmartContractAddress\x12\x1c\n" +
	"\tTimeStamp\x18\t \x01(\x03R\tTimeStamp\"\x83\x01\n" +
	"\x05Block\x12\x1c\n" +
	"\tBlockHash\x18\x01 \x01(\tR\tBlockHash\x12-\n" +
	"\tBlockMeta\x18\x02 \x01(\v2\x0f.gate.BlockMetaR\tBlockMeta\x12-\n" +
	"\tBlockData\x18\x03 \x01(\v2\x0f.gate.BlockDataR\tBlockData\"?\n" +
	"\rAddDataResult\x12\x1c\n" +
	"\tIsSuccess\x18\x01 \x01(\bR\tIsSuccess\x12\x10\n" +
	"\x03Log\x18\x02 \x01(\tR\x03Log\"\xbb\x03\n" +
	"\x0fReadDataRequest\x12\x14\n" +
	"\x05Limit\x18\x01 \x01(\x03R\x05Limit\x12\x12\n" +
	"\x04Skip\x18\x02 \x01(\x03R\x04Skip\x12\x1c\n" +
	"\tSenderUID\x18\x03 \x01(\tR\tSenderUID\x12\x1e\n" +
	"\n" +
	"SenderRole\x18\x04 \x01(\x03R\n" +
	"SenderRole\x12\"\n" +
	"\fSenderPubKey\x18\x05 \x01(\tR\fSenderPubKey\x12 \n" +
	"\vReceiverUID\x18\x06 \x01(\tR\vReceiverUID\x12\"\n" +
	"\fReceiverRole\x18\a \x01(\x03R\fReceiverRole\x12\x1c\n" +
	"\tBlockHash\x18\b \x01(\tR\tBlockHash\x12\"\n" +
	"\fPreBlockHash\x18\t \x01(\tR\fPreBlockHash\x12\x18\n" +
	"\aNodeUID\x18\n" +
	" \x01(\tR\aNodeUID\x12$\n" +
	"\rTimeStampFrom\x18\v \x01(\x03R\rTimeStampFrom\x12 \n" +
	"\vTimeStampTo\x18\f \x01(\x03R\vTimeStampTo\x122\n" +
	"\x14SmartContractAddress\x18\r \x01(\tR\x14SmartContractAddress\"a\n" +
	"\x0eReadDataResult\x12\x1c\n" +
	"\tIsSuccess\x18\x01 \x01(\bR\tIsSuccess\x12\x10\n" +
	"\x03Log\x18\x02 \x01(\tR\x03Log\x12\x1f\n" +
	"\x04Data\x18\x03 \x03(\v2\v.gate.BlockR\x04Data2:\n" +
	"\aAddData\x12/\n" +
	"\aaddData\x12\x0f.gate.BlockData\x1a\x13.gate.AddDataResult2C\n" +
	"\bReadData\x127\n" +
	"\breadData\x12\x15.gate.ReadDataRequest\x1a\x14.gate.ReadDataResultB\x16Z\x14blvchain/core/protosb\x06proto3"

var (
	file_protos_gate_proto_rawDescOnce sync.Once
	file_protos_gate_proto_rawDescData []byte
)

func file_protos_gate_proto_rawDescGZIP() []byte {
	file_protos_gate_proto_rawDescOnce.Do(func() {
		file_protos_gate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_gate_proto_rawDesc), len(file_protos_gate_proto_rawDesc)))
	})
	return file_protos_gate_proto_rawDescData
}

var file_protos_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_gate_proto_goTypes = []any{
	(*BlockMeta)(nil),       // 0: gate.BlockMeta
	(*BlockData)(nil),       // 1: gate.BlockData
	(*Block)(nil),           // 2: gate.Block
	(*AddDataResult)(nil),   // 3: gate.AddDataResult
	(*ReadDataRequest)(nil), // 4: gate.ReadDataRequest
	(*ReadDataResult)(nil),  // 5: gate.ReadDataResult
}
var file_protos_gate_proto_depIdxs = []int32{
	0, // 0: gate.Block.BlockMeta:type_name -> gate.BlockMeta
	1, // 1: gate.Block.BlockData:type_name -> gate.BlockData
	2, // 2: gate.ReadDataResult.Data:type_name -> gate.Block
	1, // 3: gate.AddData.addData:input_type -> gate.BlockData
	4, // 4: gate.ReadData.readData:input_type -> gate.ReadDataRequest
	3, // 5: gate.AddData.addData:output_type -> gate.AddDataResult
	5, // 6: gate.ReadData.readData:output_type -> gate.ReadDataResult
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_gate_proto_init() }
func file_protos_gate_proto_init() {
	if File_protos_gate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_gate_proto_rawDesc), len(file_protos_gate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protos_gate_proto_goTypes,
		DependencyIndexes: file_protos_gate_proto_depIdxs,
		MessageInfos:      file_protos_gate_proto_msgTypes,
	}.Build()
	File_protos_gate_proto = out.File
	file_protos_gate_proto_goTypes = nil
	file_protos_gate_proto_depIdxs = nil
}
