// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: protos/gate.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AddData_AddData_FullMethodName = "/gate.AddData/addData"
)

// AddDataClient is the client API for AddData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Add data
type AddDataClient interface {
	AddData(ctx context.Context, in *BlockData, opts ...grpc.CallOption) (*AddDataResult, error)
}

type addDataClient struct {
	cc grpc.ClientConnInterface
}

func NewAddDataClient(cc grpc.ClientConnInterface) AddDataClient {
	return &addDataClient{cc}
}

func (c *addDataClient) AddData(ctx context.Context, in *BlockData, opts ...grpc.CallOption) (*AddDataResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDataResult)
	err := c.cc.Invoke(ctx, AddData_AddData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddDataServer is the server API for AddData service.
// All implementations must embed UnimplementedAddDataServer
// for forward compatibility.
//
// Add data
type AddDataServer interface {
	AddData(context.Context, *BlockData) (*AddDataResult, error)
	mustEmbedUnimplementedAddDataServer()
}

// UnimplementedAddDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddDataServer struct{}

func (UnimplementedAddDataServer) AddData(context.Context, *BlockData) (*AddDataResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddData not implemented")
}
func (UnimplementedAddDataServer) mustEmbedUnimplementedAddDataServer() {}
func (UnimplementedAddDataServer) testEmbeddedByValue()                 {}

// UnsafeAddDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddDataServer will
// result in compilation errors.
type UnsafeAddDataServer interface {
	mustEmbedUnimplementedAddDataServer()
}

func RegisterAddDataServer(s grpc.ServiceRegistrar, srv AddDataServer) {
	// If the following call pancis, it indicates UnimplementedAddDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AddData_ServiceDesc, srv)
}

func _AddData_AddData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddDataServer).AddData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddData_AddData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddDataServer).AddData(ctx, req.(*BlockData))
	}
	return interceptor(ctx, in, info, handler)
}

// AddData_ServiceDesc is the grpc.ServiceDesc for AddData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gate.AddData",
	HandlerType: (*AddDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addData",
			Handler:    _AddData_AddData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/gate.proto",
}

const (
	ReadData_ReadData_FullMethodName = "/gate.ReadData/readData"
)

// ReadDataClient is the client API for ReadData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Read data
type ReadDataClient interface {
	ReadData(ctx context.Context, in *ReadDataRequest, opts ...grpc.CallOption) (*ReadDataResult, error)
}

type readDataClient struct {
	cc grpc.ClientConnInterface
}

func NewReadDataClient(cc grpc.ClientConnInterface) ReadDataClient {
	return &readDataClient{cc}
}

func (c *readDataClient) ReadData(ctx context.Context, in *ReadDataRequest, opts ...grpc.CallOption) (*ReadDataResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadDataResult)
	err := c.cc.Invoke(ctx, ReadData_ReadData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReadDataServer is the server API for ReadData service.
// All implementations must embed UnimplementedReadDataServer
// for forward compatibility.
//
// Read data
type ReadDataServer interface {
	ReadData(context.Context, *ReadDataRequest) (*ReadDataResult, error)
	mustEmbedUnimplementedReadDataServer()
}

// UnimplementedReadDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReadDataServer struct{}

func (UnimplementedReadDataServer) ReadData(context.Context, *ReadDataRequest) (*ReadDataResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadData not implemented")
}
func (UnimplementedReadDataServer) mustEmbedUnimplementedReadDataServer() {}
func (UnimplementedReadDataServer) testEmbeddedByValue()                  {}

// UnsafeReadDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReadDataServer will
// result in compilation errors.
type UnsafeReadDataServer interface {
	mustEmbedUnimplementedReadDataServer()
}

func RegisterReadDataServer(s grpc.ServiceRegistrar, srv ReadDataServer) {
	// If the following call pancis, it indicates UnimplementedReadDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReadData_ServiceDesc, srv)
}

func _ReadData_ReadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadDataServer).ReadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadData_ReadData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadDataServer).ReadData(ctx, req.(*ReadDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReadData_ServiceDesc is the grpc.ServiceDesc for ReadData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReadData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gate.ReadData",
	HandlerType: (*ReadDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "readData",
			Handler:    _ReadData_ReadData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/gate.proto",
}
