// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protos/gate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block
type BlockMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreBlockHash  []byte                 `protobuf:"bytes,1,opt,name=PreBlockHash,proto3" json:"PreBlockHash,omitempty"`
	NodeUID       []byte                 `protobuf:"bytes,2,opt,name=NodeUID,proto3" json:"NodeUID,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockMeta) Reset() {
	*x = BlockMeta{}
	mi := &file_protos_gate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMeta) ProtoMessage() {}

func (x *BlockMeta) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMeta.ProtoReflect.Descriptor instead.
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{0}
}

func (x *BlockMeta) GetPreBlockHash() []byte {
	if x != nil {
		return x.PreBlockHash
	}
	return nil
}

func (x *BlockMeta) GetNodeUID() []byte {
	if x != nil {
		return x.NodeUID
	}
	return nil
}

func (x *BlockMeta) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type Contract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          []byte                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Version       []byte                 `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Language      []byte                 `protobuf:"bytes,3,opt,name=Language,proto3" json:"Language,omitempty"`
	Compiler      []byte                 `protobuf:"bytes,4,opt,name=Compiler,proto3" json:"Compiler,omitempty"`
	Description   []byte                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	Checksum      []byte                 `protobuf:"bytes,6,opt,name=Checksum,proto3" json:"Checksum,omitempty"`
	Author        []byte                 `protobuf:"bytes,7,opt,name=Author,proto3" json:"Author,omitempty"`
	License       []byte                 `protobuf:"bytes,8,opt,name=License,proto3" json:"License,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_protos_gate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{1}
}

func (x *Contract) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Contract) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Contract) GetLanguage() []byte {
	if x != nil {
		return x.Language
	}
	return nil
}

func (x *Contract) GetCompiler() []byte {
	if x != nil {
		return x.Compiler
	}
	return nil
}

func (x *Contract) GetDescription() []byte {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Contract) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *Contract) GetAuthor() []byte {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Contract) GetLicense() []byte {
	if x != nil {
		return x.License
	}
	return nil
}

type BlockData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderUID      []byte                 `protobuf:"bytes,1,opt,name=SenderUID,proto3" json:"SenderUID,omitempty"`
	SenderPubKey   []byte                 `protobuf:"bytes,2,opt,name=SenderPubKey,proto3" json:"SenderPubKey,omitempty"`
	Signature      []byte                 `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	ReceiverUID    []byte                 `protobuf:"bytes,4,opt,name=ReceiverUID,proto3" json:"ReceiverUID,omitempty"`
	Data           []byte                 `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
	ContractBase64 []byte                 `protobuf:"bytes,6,opt,name=ContractBase64,proto3" json:"ContractBase64,omitempty"`
	UseContract    []byte                 `protobuf:"bytes,7,opt,name=UseContract,proto3" json:"UseContract,omitempty"`
	ContractData   *Contract              `protobuf:"bytes,8,opt,name=ContractData,proto3" json:"ContractData,omitempty"`
	TimeStamp      int64                  `protobuf:"varint,9,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockData) Reset() {
	*x = BlockData{}
	mi := &file_protos_gate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockData) ProtoMessage() {}

func (x *BlockData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockData.ProtoReflect.Descriptor instead.
func (*BlockData) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{2}
}

func (x *BlockData) GetSenderUID() []byte {
	if x != nil {
		return x.SenderUID
	}
	return nil
}

func (x *BlockData) GetSenderPubKey() []byte {
	if x != nil {
		return x.SenderPubKey
	}
	return nil
}

func (x *BlockData) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *BlockData) GetReceiverUID() []byte {
	if x != nil {
		return x.ReceiverUID
	}
	return nil
}

func (x *BlockData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BlockData) GetContractBase64() []byte {
	if x != nil {
		return x.ContractBase64
	}
	return nil
}

func (x *BlockData) GetUseContract() []byte {
	if x != nil {
		return x.UseContract
	}
	return nil
}

func (x *BlockData) GetContractData() *Contract {
	if x != nil {
		return x.ContractData
	}
	return nil
}

func (x *BlockData) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     []byte                 `protobuf:"bytes,1,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	BlockMeta     *BlockMeta             `protobuf:"bytes,2,opt,name=BlockMeta,proto3" json:"BlockMeta,omitempty"`
	BlockData     *BlockData             `protobuf:"bytes,3,opt,name=BlockData,proto3" json:"BlockData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_protos_gate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{3}
}

func (x *Block) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *Block) GetBlockMeta() *BlockMeta {
	if x != nil {
		return x.BlockMeta
	}
	return nil
}

func (x *Block) GetBlockData() *BlockData {
	if x != nil {
		return x.BlockData
	}
	return nil
}

type AddDataResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
	Log           string                 `protobuf:"bytes,2,opt,name=Log,proto3" json:"Log,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,3,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDataResult) Reset() {
	*x = AddDataResult{}
	mi := &file_protos_gate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDataResult) ProtoMessage() {}

func (x *AddDataResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDataResult.ProtoReflect.Descriptor instead.
func (*AddDataResult) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{4}
}

func (x *AddDataResult) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *AddDataResult) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *AddDataResult) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

type ReadDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Skip          int64                  `protobuf:"varint,2,opt,name=Skip,proto3" json:"Skip,omitempty"`
	SenderUID     []byte                 `protobuf:"bytes,3,opt,name=SenderUID,proto3" json:"SenderUID,omitempty"`
	SenderPubKey  []byte                 `protobuf:"bytes,4,opt,name=SenderPubKey,proto3" json:"SenderPubKey,omitempty"`
	ReceiverUID   []byte                 `protobuf:"bytes,5,opt,name=ReceiverUID,proto3" json:"ReceiverUID,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,6,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	PreBlockHash  []byte                 `protobuf:"bytes,7,opt,name=PreBlockHash,proto3" json:"PreBlockHash,omitempty"`
	NodeUID       []byte                 `protobuf:"bytes,8,opt,name=NodeUID,proto3" json:"NodeUID,omitempty"`
	TimeStampFrom int64                  `protobuf:"varint,9,opt,name=TimeStampFrom,proto3" json:"TimeStampFrom,omitempty"`
	TimeStampTo   int64                  `protobuf:"varint,10,opt,name=TimeStampTo,proto3" json:"TimeStampTo,omitempty"`
	UseContract   []byte                 `protobuf:"bytes,11,opt,name=UseContract,proto3" json:"UseContract,omitempty"`
	UID           []byte                 `protobuf:"bytes,12,opt,name=UID,proto3" json:"UID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDataRequest) Reset() {
	*x = ReadDataRequest{}
	mi := &file_protos_gate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataRequest) ProtoMessage() {}

func (x *ReadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataRequest.ProtoReflect.Descriptor instead.
func (*ReadDataRequest) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{5}
}

func (x *ReadDataRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReadDataRequest) GetSkip() int64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ReadDataRequest) GetSenderUID() []byte {
	if x != nil {
		return x.SenderUID
	}
	return nil
}

func (x *ReadDataRequest) GetSenderPubKey() []byte {
	if x != nil {
		return x.SenderPubKey
	}
	return nil
}

func (x *ReadDataRequest) GetReceiverUID() []byte {
	if x != nil {
		return x.ReceiverUID
	}
	return nil
}

func (x *ReadDataRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ReadDataRequest) GetPreBlockHash() []byte {
	if x != nil {
		return x.PreBlockHash
	}
	return nil
}

func (x *ReadDataRequest) GetNodeUID() []byte {
	if x != nil {
		return x.NodeUID
	}
	return nil
}

func (x *ReadDataRequest) GetTimeStampFrom() int64 {
	if x != nil {
		return x.TimeStampFrom
	}
	return 0
}

func (x *ReadDataRequest) GetTimeStampTo() int64 {
	if x != nil {
		return x.TimeStampTo
	}
	return 0
}

func (x *ReadDataRequest) GetUseContract() []byte {
	if x != nil {
		return x.UseContract
	}
	return nil
}

func (x *ReadDataRequest) GetUID() []byte {
	if x != nil {
		return x.UID
	}
	return nil
}

type ReadDataResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
	Log           string                 `protobuf:"bytes,2,opt,name=Log,proto3" json:"Log,omitempty"`
	Data          []*Block               `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDataResult) Reset() {
	*x = ReadDataResult{}
	mi := &file_protos_gate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataResult) ProtoMessage() {}

func (x *ReadDataResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataResult.ProtoReflect.Descriptor instead.
func (*ReadDataResult) Descriptor() ([]byte, []int) {
	return file_protos_gate_proto_rawDescGZIP(), []int{6}
}

func (x *ReadDataResult) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *ReadDataResult) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *ReadDataResult) GetData() []*Block {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_protos_gate_proto protoreflect.FileDescriptor

const file_protos_gate_proto_rawDesc = "" +
	"\n" +
	"\x11protos/gate.proto\x12\x04gate\"g\n" +
	"\tBlockMeta\x12\"\n" +
	"\fPreBlockHash\x18\x01 \x01(\fR\fPreBlockHash\x12\x18\n" +
	"\aNodeUID\x18\x02 \x01(\fR\aNodeUID\x12\x1c\n" +
	"\tTimeStamp\x18\x03 \x01(\x03R\tTimeStamp\"\xe0\x01\n" +
	"\bContract\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\fR\x04Name\x12\x18\n" +
	"\aVersion\x18\x02 \x01(\fR\aVersion\x12\x1a\n" +
	"\bLanguage\x18\x03 \x01(\fR\bLanguage\x12\x1a\n" +
	"\bCompiler\x18\x04 \x01(\fR\bCompiler\x12 \n" +
	"\vDescription\x18\x05 \x01(\fR\vDescription\x12\x1a\n" +
	"\bChecksum\x18\x06 \x01(\fR\bChecksum\x12\x16\n" +
	"\x06Author\x18\a \x01(\fR\x06Author\x12\x18\n" +
	"\aLicense\x18\b \x01(\fR\aLicense\"\xbd\x02\n" +
	"\tBlockData\x12\x1c\n" +
	"\tSenderUID\x18\x01 \x01(\fR\tSenderUID\x12\"\n" +
	"\fSenderPubKey\x18\x02 \x01(\fR\fSenderPubKey\x12\x1c\n" +
	"\tSignature\x18\x03 \x01(\fR\tSignature\x12 \n" +
	"\vReceiverUID\x18\x04 \x01(\fR\vReceiverUID\x12\x12\n" +
	"\x04Data\x18\x05 \x01(\fR\x04Data\x12&\n" +
	"\x0eContractBase64\x18\x06 \x01(\fR\x0eContractBase64\x12 \n" +
	"\vUseContract\x18\a \x01(\fR\vUseContract\x122\n" +
	"\fContractData\x18\b \x01(\v2\x0e.gate.ContractR\fContractData\x12\x1c\n" +
	"\tTimeStamp\x18\t \x01(\x03R\tTimeStamp\"\x83\x01\n" +
	"\x05Block\x12\x1c\n" +
	"\tBlockHash\x18\x01 \x01(\fR\tBlockHash\x12-\n" +
	"\tBlockMeta\x18\x02 \x01(\v2\x0f.gate.BlockMetaR\tBlockMeta\x12-\n" +
	"\tBlockData\x18\x03 \x01(\v2\x0f.gate.BlockDataR\tBlockData\"]\n" +
	"\rAddDataResult\x12\x1c\n" +
	"\tIsSuccess\x18\x01 \x01(\bR\tIsSuccess\x12\x10\n" +
	"\x03Log\x18\x02 \x01(\tR\x03Log\x12\x1c\n" +
	"\tBlockHash\x18\x03 \x01(\fR\tBlockHash\"\xf7\x02\n" +
	"\x0fReadDataRequest\x12\x14\n" +
	"\x05Limit\x18\x01 \x01(\x03R\x05Limit\x12\x12\n" +
	"\x04Skip\x18\x02 \x01(\x03R\x04Skip\x12\x1c\n" +
	"\tSenderUID\x18\x03 \x01(\fR\tSenderUID\x12\"\n" +
	"\fSenderPubKey\x18\x04 \x01(\fR\fSenderPubKey\x12 \n" +
	"\vReceiverUID\x18\x05 \x01(\fR\vReceiverUID\x12\x1c\n" +
	"\tBlockHash\x18\x06 \x01(\fR\tBlockHash\x12\"\n" +
	"\fPreBlockHash\x18\a \x01(\fR\fPreBlockHash\x12\x18\n" +
	"\aNodeUID\x18\b \x01(\fR\aNodeUID\x12$\n" +
	"\rTimeStampFrom\x18\t \x01(\x03R\rTimeStampFrom\x12 \n" +
	"\vTimeStampTo\x18\n" +
	" \x01(\x03R\vTimeStampTo\x12 \n" +
	"\vUseContract\x18\v \x01(\fR\vUseContract\x12\x10\n" +
	"\x03UID\x18\f \x01(\fR\x03UID\"a\n" +
	"\x0eReadDataResult\x12\x1c\n" +
	"\tIsSuccess\x18\x01 \x01(\bR\tIsSuccess\x12\x10\n" +
	"\x03Log\x18\x02 \x01(\tR\x03Log\x12\x1f\n" +
	"\x04Data\x18\x03 \x03(\v2\v.gate.BlockR\x04Data2:\n" +
	"\aAddData\x12/\n" +
	"\aaddData\x12\x0f.gate.BlockData\x1a\x13.gate.AddDataResult2C\n" +
	"\bReadData\x127\n" +
	"\breadData\x12\x15.gate.ReadDataRequest\x1a\x14.gate.ReadDataResultB\x16Z\x14blvchain/core/protosb\x06proto3"

var (
	file_protos_gate_proto_rawDescOnce sync.Once
	file_protos_gate_proto_rawDescData []byte
)

func file_protos_gate_proto_rawDescGZIP() []byte {
	file_protos_gate_proto_rawDescOnce.Do(func() {
		file_protos_gate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_gate_proto_rawDesc), len(file_protos_gate_proto_rawDesc)))
	})
	return file_protos_gate_proto_rawDescData
}

var file_protos_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_gate_proto_goTypes = []any{
	(*BlockMeta)(nil),       // 0: gate.BlockMeta
	(*Contract)(nil),        // 1: gate.Contract
	(*BlockData)(nil),       // 2: gate.BlockData
	(*Block)(nil),           // 3: gate.Block
	(*AddDataResult)(nil),   // 4: gate.AddDataResult
	(*ReadDataRequest)(nil), // 5: gate.ReadDataRequest
	(*ReadDataResult)(nil),  // 6: gate.ReadDataResult
}
var file_protos_gate_proto_depIdxs = []int32{
	1, // 0: gate.BlockData.ContractData:type_name -> gate.Contract
	0, // 1: gate.Block.BlockMeta:type_name -> gate.BlockMeta
	2, // 2: gate.Block.BlockData:type_name -> gate.BlockData
	3, // 3: gate.ReadDataResult.Data:type_name -> gate.Block
	2, // 4: gate.AddData.addData:input_type -> gate.BlockData
	5, // 5: gate.ReadData.readData:input_type -> gate.ReadDataRequest
	4, // 6: gate.AddData.addData:output_type -> gate.AddDataResult
	6, // 7: gate.ReadData.readData:output_type -> gate.ReadDataResult
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_gate_proto_init() }
func file_protos_gate_proto_init() {
	if File_protos_gate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_gate_proto_rawDesc), len(file_protos_gate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protos_gate_proto_goTypes,
		DependencyIndexes: file_protos_gate_proto_depIdxs,
		MessageInfos:      file_protos_gate_proto_msgTypes,
	}.Build()
	File_protos_gate_proto = out.File
	file_protos_gate_proto_goTypes = nil
	file_protos_gate_proto_depIdxs = nil
}
